nol-jo/nolzo-ticket-backend

.gitignore, build.gradle, src/main/java/com/noljo/nolzo/event/entity/Event.java, src/main/java/com/noljo/nolzo/event/repository/EventRepository.java, src/main/java/com/noljo/nolzo/global/BaseEntity.java, src/main/java/com/noljo/nolzo/global/config/JpaConfig.java, src/main/java/com/noljo/nolzo/member/entity/Member.java, src/main/java/com/noljo/nolzo/reservation/entity/Reservation.java, src/main/java/com/noljo/nolzo/seat/entity/Seat.java, src/main/java/com/noljo/nolzo/seat/repository/SeatRepository.java, src/main/java/com/noljo/nolzo/ticket/controller/TicketController.java, src/main/java/com/noljo/nolzo/ticket/dto/TicketResponse.java, src/main/java/com/noljo/nolzo/ticket/entity/Ticket.java, src/main/java/com/noljo/nolzo/ticket/service/TicketService.java, src/main/resources/application.yml, src/test/java/com/noljo/nolzo/domain/member/service/MemberServiceTest.java, src/test/java/com/noljo/nolzo/domain/seat/service/SeatServiceTest.java, src/test/java/com/noljo/nolzo/domain/ticket/service/TicketServiceTest.java, src/test/java/com/noljo/nolzo/support/DatabaseCleaner.java, src/test/java/com/noljo/nolzo/support/DatabaseCleanerExtension.java, src/test/java/com/noljo/nolzo/support/SystemTableName.java, src/test/java/com/noljo/nolzo/support/annotation/ServiceTest.java, src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java, src/test/java/com/noljo/nolzo/support/fixture/MemberFixture.java, src/test/java/com/noljo/nolzo/support/fixture/ReservationFixture.java, src/test/java/com/noljo/nolzo/support/fixture/SeatFixture.java, src/test/java/com/noljo/nolzo/support/fixture/TicketFixture.java, src/test/resources/application-test.yml
* (작업한 코드에 대한 간략한 설명해주세요)
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
- jpa 설정을 위한 config가 등록이 되어있지 않아 추가 했습니다.
- 회원 id 기반으로 지금까지 예매했던 티켓 내역을 조회하는 기능을 추가 했지만, 추후 인증토큰을 통해 넘겨주는 정보에 따라 수정될 가능성이 있습니다. 
- 티켓 상세조회기능 구현했습니다.
* 테스트 시 모든 데이터를 삭제해주고, 데이터 정합성을 위한 어노테이션을 임시로 주석처리 후 추가했습니다. 토의 후 마저 완성할 것 같습니다.
* 테스트 전용 프로파일을 추가해야할 것 같습니다.
| 이미지① |
| :----: |
| |
---
=> [Feature] 티켓 조회기능 구현 #1

src/main/java/com/noljo/nolzo/payment/controller/PaymentController.java, src/main/java/com/noljo/nolzo/payment/dto/PaymentRequest.java, src/main/java/com/noljo/nolzo/payment/dto/PaymentResponse.java, src/main/java/com/noljo/nolzo/payment/entity/Payment.java, src/main/java/com/noljo/nolzo/payment/entity/PaymentMethod.java, src/main/java/com/noljo/nolzo/payment/repository/PaymentRepository.java, src/main/java/com/noljo/nolzo/payment/service/PaymentService.java, src/main/java/com/noljo/nolzo/reservation/repository/ReservationRepository.java, src/main/java/com/noljo/nolzo/ticket/dto/TicketResponse.java, src/test/java/com/noljo/nolzo/domain/payment/service/PaymentServiceTest.java, src/test/java/com/noljo/nolzo/support/fixture/PaymentFixture.java
* (작업한 코드에 대한 간략한 설명해주세요)
- 결제를 직접 PG사 외부 api를 연동하지 않고 임의로 결제했다고만 하기로 했기때문에 예약정보와, 회원정보가 넘어올 시 바로 데이터가 생성되도록 했습니다.  
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
- MemberRepository에 있는 default 메서드를 ReservationRepository에도 추가했습니다. 
-  -  -  -  - 여러 service클래스에서 사용될 것 같아서 추가했습니다.
* (작업한 코드가 추후 우리 프로젝트에 어떤 영향을 끼칠지, 앞으로 PR계획을 설명해주세요)
-  예약을 추가하는 로직이 아직 없어 임의로 구현했지만, 예약 추가기능이 현재 구현한 내용과 맞지않을 경우 수정할 가능성이 있습니다
- 올바른 회원과 유저의 정보가 넘어왔을 경우 결제가 추가되는 테스트를 작성했습니다.
---
=> [Feature] 결제 데이터 추가기능 구현

build.gradle, src/main/java/com/noljo/nolzo/auth/config/CorsConfig.java, src/main/java/com/noljo/nolzo/auth/config/SecurityConfig.java, src/main/java/com/noljo/nolzo/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/noljo/nolzo/auth/jwt/JwtUtil.java, src/main/java/com/noljo/nolzo/auth/security/CustomUserDetails.java, src/main/java/com/noljo/nolzo/member/entity/Member.java, src/main/java/com/noljo/nolzo/member/entity/Role.java, src/main/java/com/noljo/nolzo/member/repository/MemberRepository.java, src/test/java/com/noljo/nolzo/auth/jwt/JwtUtilTest.java, src/test/java/com/noljo/nolzo/support/fixture/MemberFixture.java
spring security 초기 설정과 JWT 필터 기능 구현
- url 별로 인증, 인가 처리는 각 도메인 별 url이 얼추 완성 되면 추후 계발 예정입니다.
- Cors은 아직 프론트가 완성이 안되서 설정 파일만 구현했습니다.
- JWT 토큰의 payload에는 {memberId, email, Role, 발행일, 만료일} 정보가 들어갑니다. 혹시 이후 변경사항 있으면 수정하겠습니다.
- 회원 가입
- accessToken/ refreshToken 발행
- 로그인/ 로그아웃
* 회원 정보로 발급한 JWT의 내용이 일치 하는지 테스트
=> [Feature] spring security 초기 설정

src/main/java/com/noljo/nolzo/event/dto/EventRequest.java, src/main/java/com/noljo/nolzo/event/dto/EventResponse.java, src/main/java/com/noljo/nolzo/event/entity/Event.java, src/main/java/com/noljo/nolzo/event/entity/Schedule.java, src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java
기존 Event 엔티티에 @Embedded 형태로 Schedule을 포함시켜 요일, 시간대 및 상영시간 필드를 추가하였습니다. 
---
=> [Refactor] Schedule 클래스 추가 및 Event 관련 로직 수정

src/main/java/com/noljo/nolzo/auth/config/SecurityConfig.java, src/main/java/com/noljo/nolzo/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/noljo/nolzo/auth/jwt/JwtUtil.java, src/main/java/com/noljo/nolzo/auth/security/CustomUserDetails.java, src/main/java/com/noljo/nolzo/auth/security/CustomUserDetailsService.java, src/test/java/com/noljo/nolzo/auth/jwt/JwtUtilTest.java
해더에서 받은 토큰을 인증하는 로직을 구현했습니다.
헤더로 넘어온 AccessToken이 유효하면 인증에 성공하고 정상적으로 스프링 시큐리티 필터를 통과하게 됩니다.
인증이 통과된 유저를 컨트롤러에서 사용하시려면
``` java
@GetMapping
public ResponseEntity<?> profile(@AuthenticationPrincipal CustomUserDetails user) {
Long memberId = user.getMemberId();
// …  
return ResponseEntity.ok( );
}
``` 
로 사용하시거나
```java
@GetMapping
public ResponseEntity<?> profile(@AuthenticationPrincipal(expression = "memberId") Long memberId) {
// … 
return ResponseEntity.ok( );
}
``` 
로 memberId 값을 파라미터로 가져올 수 있습니다.
토큰 검증하는 로직이 부족해서 추가해서 구현하였습니다.
- 헤더에서 받은 AccessToken이 적절하지 않을 경우 401 or 403 상태코드 전송 로직 구현
- AccessToken이 만료되고 RefreshToken이 유효한 경우 AccessToken 재발급 로직 구현
- AccessToken와 RefreshToken이 둘다 만료된 경우 401 상태코드 전송 로직 구현
- RefreshToken을 DB에서 제거하는 로직 구현
- Controller 계층에서 인증 로직 테스트 코드 작성
📌 리뷰어가 확인해야 할 추가 …
=> [Feature] 토큰 인증 로직 구현

src/main/java/com/noljo/nolzo/auth/dto/TokenResponse.java, src/main/java/com/noljo/nolzo/auth/jwt/JwtUtil.java, src/main/java/com/noljo/nolzo/auth/repository/InMemoryRefreshTokenRepository.java, src/main/java/com/noljo/nolzo/auth/repository/RefreshTokenRepository.java, src/main/java/com/noljo/nolzo/auth/service/JwtTokenService.java, src/test/java/com/noljo/nolzo/auth/service/JwtTokenServiceTest.java
Token 발행 기능 구현
- AccessToken, RefreshToken 발행 로직 구현
- AccessToken 재발급 로직 구현
- 기존에 시간 단위가 혼동되서 Duration으로 변경했습니다.
- 로그인/ 로그아웃 기능 구현
- refreshTokenRepository 구현체 변경
- 제가 생각한 대략적인 로그인 요청 흐름입니다 혹시 부족한 부분있으면 피드백 부탁드립니다.
- refreshToken 저장소가 아직 결정되지 않아서 일단은 인메모리 기반 저장소로 구현했습니다.
향후 멘토링과 회의를 통해서 Redis, mysql와 같은 저장소로 변경할 예정입니다.
---
Close
=> [Feature] 토큰 발행 기능 구현

src/main/java/com/noljo/nolzo/event/controller/EventController.java, src/main/java/com/noljo/nolzo/event/repository/EventRepository.java, src/main/java/com/noljo/nolzo/event/service/EventService.java
키워드를 입력받아 해당 문자열이 포함된 이벤트 제목을 검색하여 리스트로 반환하는 기능을 구현했습니다.
---
=> [Feature] 키워드 기반 이벤트 검색 기능 구현

src/main/java/com/noljo/nolzo/member/controller/MemberController.java, src/main/java/com/noljo/nolzo/member/dto/MemberDto.java, src/main/java/com/noljo/nolzo/member/service/MemberService.java
- 로그인한 사용자의 정보를 조회할 수 있는 GET /member API를 구현하였습니다.
- @AuthenticationPrincipal을 활용해 인증된 사용자의 memberId를 추출하여 응답합니다.
- MemberDto 생성: Member 엔티티 기반 응답용 DTO 작성
- MemberService.readMember() 구현: memberId로 회원 정보 조회
- MemberController.getMember() 구현: 인증된 사용자의 정보를 반환하는 API 작성
- Member 엔티티의 정보를 클라이언트에 전달하기 위한 DTO입니다.
- 비밀번호 등 민감한 필드는 포함하지 않도록 구성했습니다.
```
@Getter
@Builder
public class MemberDto {
private Long id;
private String name;
private String email;
private LocalDate birth;
private Role role;
public static MemberDto from(Member member) {
return MemberDto.builder()
.id(member.getId())
.name(member.getName())
.email(member.getEmail())
.birth(member.getBirth())
.role(member.getRole())
.build();
}
}
```
- readMember(Long memberId) 메서드는 ID를 기준으로 회원 정보를 조회합니다.
- 존재하지 않을 경우 IllegalArgumentException을 …
=> [Feature] 회원 단건 조회 API 구현

.gitignore, build.gradle, src/main/java/com/noljo/nolzo/event/controller/EventController.java, src/main/java/com/noljo/nolzo/event/dto/EventRequest.java, src/main/java/com/noljo/nolzo/event/entity/Event.java, src/main/java/com/noljo/nolzo/event/service/EventService.java, src/main/java/com/noljo/nolzo/global/config/S3Config.java, src/main/java/com/noljo/nolzo/global/upload/S3Uploader.java, src/main/resources/application.yml
- 사용자가 이미지 또는 파일을 업로드하면, 해당 파일은 AWS S3 버킷에 저장됩니다.
- s3 관련 builde.grade 추가
- S3 관련 프로퍼티 및 yml 파일 설정
- S3Uploader 유틸 클래스 구현
- 이벤트 생성 관련 로직 리팩토링 
- 기능 정상 동작
- 새로운 의존성 추가 (`build.gradle`,`application.yml`)
- 코드 스타일 및 컨벤션 준수
- 기존 테스트 통과
- 파일이 실제 AWS S3에 저장되는지 확인
- 업로드 경로는 dirName/UUID+파일명 구조로 저장됨
- 현재는 공개 접근 권한으로 업로드됨 (추후 권한 설정 기능 고려 필요)
close #70
=> [Feature] 파일 서버 AWS S3 연결 및 관련 로직 구현

src/main/java/com/noljo/nolzo/event/repository/EventRepository.java, src/main/java/com/noljo/nolzo/event/service/EventService.java, src/test/java/com/noljo/nolzo/domain/event/service/EventServiceTest.java
키워드 기반 이벤트 검색 로직 쿼리 메서드 수정
- 유사한 제목의 더미 데이터를 활용하여 검색 기능을 검증
=> [Refactor] 키워드 기반 이벤트 조회 로직 수정

.github/workflows/cicd.yml, Dockerfile, src/test/java/com/noljo/nolzo/NolzoApplicationTests.java
ci/cd 환경을 구축해 pr merge시 자동 재배포 처리가 가능하도록 구현.
📌 부족한 부분이 있다면 지적부탁드립니다.
---
close #82
=> feat: ci/cd 환경 구축

src/main/java/com/noljo/nolzo/event/controller/EventController.java, src/main/java/com/noljo/nolzo/event/dto/EventUpdateRequest.java, src/main/java/com/noljo/nolzo/event/entity/Event.java, src/main/java/com/noljo/nolzo/event/service/EventService.java, src/main/java/com/noljo/nolzo/schedule/entity/Schedule.java
=> [Feat] 좌석 생성 로직 추가 및 스케줄 정보 수정 로직 변경

src/main/java/com/noljo/nolzo/auth/config/CorsConfig.java, src/main/java/com/noljo/nolzo/auth/controller/AuthController.java
회원 인증 과정에서 해당 토큰들을 쿠키에 담아 헤더로 전송하는 기능 구현
---
#Close 76
=> [Feature] 토큰 발급시 쿠키 저장 기능 구현

src/main/java/com/noljo/nolzo/payment/service/PaymentService.java, src/main/java/com/noljo/nolzo/reservation/entity/Reservation.java, src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java, src/main/java/com/noljo/nolzo/seat/service/SeatService.java, src/main/java/com/noljo/nolzo/ticket/entity/Ticket.java, src/main/java/com/noljo/nolzo/ticket/service/TicketService.java, src/test/java/com/noljo/nolzo/domain/payment/service/PaymentServiceTest.java
* 결제 완료 후 좌석 상태가 WAITING → RESERVED로 변경되지 않음
* 결제 완료 후 예약 상태가 PENDING → CONFIRMED로 변경되지 않음
* 결제 취소 시 좌석 상태가 WAITING → AVAILABLE로 변경되지 않음
* 결제 취소 시 예약 상태가 PENDING → CANCELLED로 변경되지 않음
* 예약 생성시 티켓 발급
* (작업한 코드가 추후 우리 프로젝트에 어떤 영향을 끼칠지, 앞으로 PR계획을 설명해주세요)
---
close #91
=> [Feature] 결제 상태에 따른 좌석 상태 변경기능 구현 및, 예약 성공 시 티켓 발급기능 구현

src/main/java/com/noljo/nolzo/event/dto/EventRequest.java, src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java
프론트엔드와 api 기준 통일을 위해
schedule 관련 필드명을 수정했습니다.
---
close #93
=> Fix: EventRequest 필드 변수명 수정

src/main/java/com/noljo/nolzo/event/dto/EventResponse.java, src/main/java/com/noljo/nolzo/event/dto/EventUpdateRequest.java, src/main/java/com/noljo/nolzo/schedule/dto/ScheduleResponse.java, src/main/java/com/noljo/nolzo/schedule/dto/internal/ScheduleInfo.java, src/test/java/com/noljo/nolzo/domain/event/service/EventServiceTest.java, src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java
이벤트 정보 및 스케줄 정보 수정 로직 테스트 코드 수정
=> [Fix] 이벤트 정보 및 스케줄 정보 수정 로직 테스트 코드 수정

src/test/java/com/noljo/nolzo/support/annotation/ServiceTest.java
* (작업한 코드에 대한 간략한 설명해주세요)
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
* (작업한 코드가 추후 우리 프로젝트에 어떤 영향을 끼칠지, 앞으로 PR계획을 설명해주세요)
| 이미지① |
| :----: |
| |
---
close #101
=> [Fix] 별도의 테스트 환경을 위한 포트번호수정

src/main/java/com/noljo/nolzo/review/controller/ReviewController.java, src/main/java/com/noljo/nolzo/review/entity/Review.java, src/main/java/com/noljo/nolzo/review/repository/ReviewRepository.java, src/main/java/com/noljo/nolzo/review/service/ReviewService.java
공연 관람 후 작성할 수 있는 리뷰 정보를 저장할 Review 엔티티를 구현하였습니다.
리뷰 등록, 조회, 수정, 삭제 기능 구현
---
#close 103
=> [Feature] 리뷰 엔티티 생성

build.gradle, src/main/java/com/noljo/nolzo/global/config/RedisConfig.java, src/main/resources/application.yml, src/test/java/com/noljo/nolzo/support/RedisTemplateTests.java
* (작업한 코드에 대한 간략한 설명해주세요)
- Redis 설정 추가
* (작업한 코드가 추후 우리 프로젝트에 어떤 영향을 끼칠지, 앞으로 PR계획을 설명해주세요)
- 각자 Redis를 사용하실 부분은 학습하셔서 Repository에 CrudRepository를 상속받으셔서 사용하시면 될 것 같습니다.
---
close: #116
=> [Feature] Redis 설정 추가

src/main/java/com/noljo/nolzo/reservation/scheduler/SchedulerConfig.java
SchedulerConfig 파일 중복 제거
---
close #122
=> [Fix] SchedulerConfig 파일 중복 제거

src/main/java/com/noljo/nolzo/event/repository/EventRepository.java, src/main/java/com/noljo/nolzo/review/controller/ReviewController.java, src/main/java/com/noljo/nolzo/review/dto/request/ReviewCreateRequest.java, src/main/java/com/noljo/nolzo/review/dto/response/ReviewResponse.java, src/main/java/com/noljo/nolzo/review/entity/Review.java, src/main/java/com/noljo/nolzo/review/repository/ReviewRepository.java, src/main/java/com/noljo/nolzo/review/service/ReviewService.java, src/test/java/com/noljo/nolzo/domain/review/service/ReviewServiceTest.java, src/test/java/com/noljo/nolzo/support/fixture/ReviewFixture.java
리뷰 생성 기능을 구현하여 사용자가 공연 이벤트에 대한 리뷰를 작성할 수 있도록 합니다.
---
=> [Feature] 리뷰 생성 기능 구현

src/main/java/com/noljo/nolzo/review/controller/ReviewController.java, src/main/java/com/noljo/nolzo/review/service/ReviewService.java, src/test/java/com/noljo/nolzo/domain/review/service/ReviewServiceTest.java
=> [Fix] Review 생성 및 수정 로직 충돌 해결

build.gradle, src/main/java/com/noljo/nolzo/auth/config/SecurityConfig.java
* 애플리케이션의 메트릭 수집을 위해 Prometheus 설정을 추가하였습니다.
---
---
* Grafana를 연동하여 메트릭 시각화 대시보드 구성 예정
* 알림 연동 및 경고 규칙(Alerting Rule) 설정 예정
---
---
- `prometheus.yml` 저장 시 권한 문제(`E212`) 발생 → `sudo` 사용으로 해결
- `docker-compose` 환경에서 `host.docker.internal` 주소를 사용하여 로컬 접근 처리
- 메트릭 표준화를 위해 Micrometer를 도입하여 Prometheus 연동
---
Closes #128
=> [Feature] 프로메테우스 모니터링 설정 추가
